config/routes.rb
Rails.application.routes.draw do
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

	root "reports#index"

	resources :reports
	delete "/reports/:id" => "reports#destroy", as: "delete_report"

	resources :users

	get "/reports/mark/:id" => "reports#mark", as: "new_report_mark"
	post "/reports/mark/:id" => "reports#set_mark"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :reports
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
		@report = Report.all
	end

	def new
		@user = User.all
		@users = []
		@user.uniq {|p| @users << ["#{p.first_name} #{p.last_name}", p.id]}
	end

	def show
		@report = Report.find(params[:id])
	end

	def create
		@report = Report.new(report_params)
		@report.save
		redirect_to @report, flash: {success: "Report added"}
	end

	def mark

	end

	def set_mark
		puts params.inspect
		@report = Report.find(params[:id])
		@report.grade = mark_params
		@report.save
		redirect_to "/"
	end

	def destroy
		@report = Report.destroy(params[:id])
		redirect_to "/"
	end

	private def report_params
		params.require(:report).permit(:title, :desc, :user_id)
	end

	def mark_params
		params.require(:mark).permit(:grade)["grade"]
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = User.all
	end

	def new

	end

	def create
		@user = User.new(report_params)
		@user.save
		redirect_to @user
		# render plain: params[:user].inspect
	end

	def show
		@user = User.find(params[:id])
	end

	private def report_params
		params.require(:user).permit(:email, :first_name, :last_name)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubySrs</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
      .navi {
          text-decoration: none !important;
          color: white !important;
          font-size: 20pt !important;
          font-style: italic !important;
      }

      li {
          text-decoration: none;
      }
  </style>

</head>

<body>

<header class="p-3 bg-dark text-white">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">

      <span class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
<!--        <img src="https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" height="40" alt="img">-->
        <%= link_to image_tag( "https://www.google.com/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png", border: 0 ), root_path %>
      </span>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li>
          <span class="navi nav-link px-2 text-white"><%= link_to "Add report", new_report_path, :class => 'navi' %></span>
        </li>
        <li>
          <span class="navi nav-link px-2 text-white"><%= link_to "Add user", new_user_path, :class => 'navi' %></span>
        </li>
      </ul>


    </div>
  </div>
</header>

<%= yield %>

<p class="m-5"></p>
</body>
</html>

app/views/reports/index.html.erb
<div class="container mt-5">

  <h1 class="text-center">All reports</h1>

  <%= button_to "Add report", new_report_path, method: :get, :class => "btn btn-outline-primary" %>

  <% @report.each do |report| %>
    <hr>
    <h2><strong><%= report.title %></strong></h2>
    <h4>User: <%= report.user.first_name %> <%= report.user.last_name %> (<%= report.user.email %>)</h4>
    <p style="font-size: 14pt; font-family: Serif,serif"><%= report.desc %></p>

    <div class="row justify-content-start">


      <% if report.grade == nil %>
        <div class="col-1">
          <%= button_to "Add mark", new_report_mark_path(:id => report.id), method: :get, :class => "btn btn-outline-warning" %>
        </div>
      <% else %>
        <div class="col-1">
          Mark: <%= report.grade %>
        </div>
      <% end %>




      <div class="col-1">
        <%= button_to "Remove", delete_report_path(:id => report.id), method: :delete, :class => "btn btn-outline-danger" %>
      </div>
    </div>
  <% end %>

</div>

app/views/reports/mark.html.erb
<div class="container mt-5">
  <h1 class="text-center display-1">Add mark</h1>

  <%= form_for :mark do |f| %>

    <p>
      Mark <br>
      <%= f.text_field :grade, :placeholder => "Enter the mark", :class => "form-control"%>
    </p>

    <div class="d-grid gap-2">
      <%= f.submit 'Set the mark', :class => 'btn btn-outline-success' %>
    </div>

  <% end %>

</div>

app/views/reports/new.html.erb
<div class="container text-center pt-5 mt-5">
  <div class="container text-start">
    <%= form_for(:report, url: reports_path, class: "form-control") do |f| %>

      <p>
        Title <br>
        <%= f.text_field :title, :placeholder => "Enter here your report title", :required => true, class: "form-control" %>
      </p>

      <p>
        Description <br>
        <%= f.text_area :desc, :required => true, :placeholder => "Enter here your report body", class: "form-control" %>
      </p>

      <p>
        <%= f.select(:user_id, @users, { :prompt => "Select the user" }, { :class => "form-select" }) %>
      </p>

      <p class="text-center d-grid gap-2">
        <%= f.submit 'Add new report', :class => 'btn btn-outline-success' %>
      </p>

    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<div class="container mt-5">
  <h1 class="display-1 text-center"><strong><%= @report.title %></strong></h1>
  <h2 class="display-5"><em>Author: <%= @report.user.first_name %> <%= @report.user.last_name %> (<%= @report.user.email %>)</em></h2>
  <h3 class="display-6"><%= @report.desc %></h3>
</div>

app/views/users/new.html.erb
<div>

  <%= form_for :user, url: users_path do |f| %>

    <p>
      Email <br>
      <%= f.text_field :email, :type => 'email', :required => true %>
    </p>

    <p>
      First name <br>
      <%= f.text_field :first_name, :required => true %>
    </p>

    <p>
      Last name <br>
      <%= f.text_field :last_name, :required => true %>
    </p>

    <p>
      <%= f.submit "Click", :class => 'btn btn-outline-success' %>
    </p>


  <% end %>
</div>

app/views/users/show.html.erb
<hr>
<h1>Email: <%= @user.email %></h1> <br>
<h2>Name: <%= @user.first_name %></h2> <br>
<h3>Last name: <%= @user.last_name %></h3> <br>
<hr>